import type { Metadata } from "next";

import { Sidebar } from "@/components/sidebar";
import { navLinks } from "@/config/links";
import { Header } from "@/views/header";
import { Footer } from "@/views/footer";

import { ContextProvider } from "./provider";

import "./globals.css";

export const metadata: Metadata = {
    title: "Banking App",
    description: "Generated by Guesmia",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ContextProvider>
                <body className={`antialiased `}>
                    <div className="container mx-auto relative">
                        <Header />
                        <main className="min-h-[calc(100vh_-160px)] container mx-auto flex gap-10 md:pt-10 px-2 ">
                            <Sidebar items={navLinks} />
                            <div className=" relative w-full h-full">
                                {children}
                            </div>
                        </main>
                        <div className="md:hidden block h-[70px]"></div>
                        <Footer />
                    </div>
                </body>
            </ContextProvider>
        </html>
    );
}
