import type { Metadata } from "next";

import { Sidebar } from "@/components/sidebar";
import { navLinks } from "@/config/links";
import { Header } from "@/views/header";
import { NavLinks } from "@/views/nav-links";

import { ContextProvider } from "./provider";

import "./globals.css";

export const metadata: Metadata = {
    title: "Banking App",
    description: "Generated by Guesmia",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ContextProvider>
                <body className={`antialiased `}>
                    <div className="container mx-auto relative">
                        <Header />
                        <main className="min-h-[calc(100vh_-160px)] container mx-auto flex gap-10 md:pt-10 px-2 ">
                            <Sidebar items={navLinks} />
                            <div className=" relative w-full h-full">
                                {children}
                            </div>
                        </main>
                        <div className="md:hidden block h-[70px]"></div>
                        <footer className="md:hidden fixed left-0 right-0 bottom-0  bg-white border-t border-t-[#222]  text-white font-bold  flex items-center justify-between px-10 py-3">
                            <NavLinks
                                items={navLinks}
                                className="w-full justify-between"
                            />
                        </footer>
                    </div>
                </body>
            </ContextProvider>
        </html>
    );
}
